export { default as Register } from "./Register";
export { default as Login } from "./Login";
export { default as Home } from "./Home";
export { default as CompetitionList } from "./CompetitionList";
export { default as Profile } from "./Profile";
export { default as About } from "./About";
export { default as EditProfile } from "./EditProfile";
export { default as CompetitionLeaderboard } from "./CompetitionLeaderboard";
export { default as CreateCompetition } from "./CreateCompetition";
